language: python
python:
  - "2.7"
install:
  - pip install -r devRequirements.txt
  - pip install pyyaml
env:
  - GAE_BASE_PATH=${HOME}/google_appengine
before_script:
  - curl -Lo google_appengine.zip https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.80.zip
  - unzip -q google_appengine.zip -d $HOME
script:
  - make init
  - make test
